car-park.WEB/Controllers/CarController.cs
using car_park.Common;
using car_park.DTO;
using car_park.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace car_park.Controllers
{
    public class CarController : BaseController
    {
        // GET: Car
        public ActionResult Index()
        {
            var result = GetWebApiResult("api/car", new List<CarDTO>());
            if (result.Count > 0)
            {
                List<CarVM> carVM = mapper.Map<List<CarVM>>(result);
                return View(carVM);
            }                
            else
                return View();
        }

        public ActionResult Details(int? ID)
        {
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = GetWebApiResult("api/car/" + ID, new CarDTO());
            if (result != null)
            {
                CarVM carVM = mapper.Map<CarVM>(result);
                return View(carVM);
            }            
            else
                return View();

        }

        public ActionResult Edit(int? ID)
        {
            CarVM carVM = new CarVM();

            if (ID.HasValue)
            {
                var result = GetWebApiResult("api/car/" + ID, new CarDTO());
                if (result != null)
                {
                    carVM = mapper.Map<CarVM>(result);
                    carVM.ColorList = GetWebApiResult("api/color", new List<ColorDTO>());
                    carVM.BrandList = GetWebApiResult("api/brand", new List<BrandDTO>());
                    //carVM.ModelList = GetWebApiResult("api/model", new List<ModelDTO>());
                    carVM.ModelList = GetWebApiResult("api/model/getbybrandid/" + carVM.BrandList.FirstOrDefault().ID, new List<ModelDTO>());
                    carVM.GarageList = GetWebApiResult("api/garage", new List<GarageDTO>());
                    return View(carVM);
                }
            }

            carVM.ColorList = GetWebApiResult("api/color", new List<ColorDTO>());
            carVM.BrandList = GetWebApiResult("api/brand", new List<BrandDTO>());
            //carVM.ModelList = GetWebApiResult("api/model", new List<ModelDTO>());
            carVM.ModelList = GetWebApiResult("api/model/getbybrandid/" + carVM.BrandList.FirstOrDefault().ID, new List<ModelDTO>());
            carVM.GarageList = GetWebApiResult("api/garage", new List<GarageDTO>());
            return View(carVM);
        }

        [HttpPost]
        public ActionResult Edit(CarVM carVM)
        {
            if (ModelState.IsValid)
            {
                HttpClient hc = GetHttpClient();

                HttpResponseMessage Response = null;

                CarDTO carDTO = mapper.Map<CarDTO>(carVM);

                if (carDTO.ID <= 0)
                    Response = hc.PostAsJsonAsync<CarDTO>("api/car", carDTO).Result;
                else
                    Response = hc.PutAsJsonAsync<CarDTO>("api/car", carDTO).Result;

                if (Response.IsSuccessStatusCode)
                {
                    var Result = Response.Content.ReadAsAsync<ApiResult>().Result;
                    if (ValidateResult(Result))
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            carVM.ColorList = GetWebApiResult("api/color", new List<ColorDTO>());
            carVM.BrandList = GetWebApiResult("api/brand", new List<BrandDTO>());
            //carVM.ModelList = GetWebApiResult("api/model", new List<ModelDTO>());
            carVM.ModelList = GetWebApiResult("api/model/getbybrandid/" + carVM.BrandList.FirstOrDefault().ID, new List<ModelDTO>());
            carVM.GarageList = GetWebApiResult("api/garage", new List<GarageDTO>());
            return View(carVM);
        }
        public ActionResult Delete(int? ID)
        {
            if (!ID.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var result = GetWebApiResult("api/car/" + ID, new CarDTO());

            if (result == null)
                return HttpNotFound();
            else
            {
                CarVM carVM = mapper.Map<CarVM>(result);
                return View(carVM);
            }
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int ID)
        {
            HttpClient hc = GetHttpClient();

            var Result = hc.DeleteAsync("api/car/" + ID).Result;

            if (Result.IsSuccessStatusCode)
            {
                var Response = Result.Content.ReadAsAsync<ApiResult>().Result;
                if (ValidateResult(Response))
                {
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }

        public ActionResult Models(int id)
        {
            var result = GetWebApiResult("api/model/getbybrandid/" + id, new List<ModelDTO>());

            return Json(
                result.Select(x => new { value = x.ID, text = x.Name }),
                JsonRequestBehavior.AllowGet
            );
        }
    }
}

car-park.WEB/Controllers/GarageController.cs
using AutoMapper;
using car_park.Common;
using car_park.DTO;
using car_park.WEB.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace car_park.Controllers
{
    public class GarageController : BaseController
    {
        // GET: Garage
        public ActionResult Index()
        {
            var result = GetWebApiResult("api/garage", new List<GarageDTO>());
            if (result.Count > 0)
            {
                List<GarageVM> garageVM = mapper.Map<List<GarageVM>>(result);
                return View(garageVM);
            }                
            else
                return View();
        }

        public ActionResult Details(int? ID)
        {
            if (ID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var result = GetWebApiResult("api/garage/" + ID, new GarageDTO());
            
            if (result != null)
            {
                GarageVM garageVM = mapper.Map<GarageVM>(result);
                return View(garageVM);

            }                
            else
                return View();

        }

        public ActionResult Edit(int? ID) {

            GarageVM garageVM = new GarageVM();

            if (ID.HasValue)
            {
                var result = GetWebApiResult("api/garage/" + ID, new GarageDTO());
                if (result != null)
                    garageVM = mapper.Map<GarageVM>(result);
            }
            return View(garageVM);
        }

        [HttpPost]
        public ActionResult Edit(GarageVM garageVM)
        {
            if (ModelState.IsValid)
            {
                HttpClient hc = GetHttpClient();

                HttpResponseMessage Response = null;

                GarageDTO garageDTO = mapper.Map<GarageDTO>(garageVM);

                if (garageDTO.ID <= 0)
                    Response = hc.PostAsJsonAsync<GarageDTO>("api/garage", garageDTO).Result;
                else
                    Response = hc.PutAsJsonAsync<GarageDTO>("api/garage", garageDTO).Result;

                if (Response.IsSuccessStatusCode)
                {
                    var Result = Response.Content.ReadAsAsync<ApiResult>().Result;
                    if (ValidateResult(Result))
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View(garageVM);
        }

        public ActionResult Delete(int? ID)
        {
            if (!ID.HasValue)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var result = GetWebApiResult("api/garage/" + ID, new GarageDTO());


            if (result == null)
                return HttpNotFound();
            else
            {
                GarageVM garageVM = mapper.Map<GarageVM>(result);
                return View(garageVM);
            }
        }

        [HttpPost, ActionName("Delete")]
        public ActionResult Delete(int ID)
        {
            HttpClient hc = GetHttpClient();

            var Result = hc.DeleteAsync("api/garage/" + ID).Result;

            if (Result.IsSuccessStatusCode)
            {
                var Response = Result.Content.ReadAsAsync<ApiResult>().Result;
                if (ValidateResult(Response))
                {
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index");
        }
    }
}

car-park.WEB/Views/Garage/Delete.cshtml
@model car_park.WEB.Models.GarageVM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GarageDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaxCar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxCar)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

car-park.WEB/Views/Garage/Details.cshtml
@model car_park.WEB.Models.GarageVM
@using GridMvc.Html

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




<h2>Details</h2>

<div>
    <h4>GarageDTO</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.MaxCar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MaxCar)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CarsInStock)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CarsInStock)
        </dd>

    </dl>
</div>

<hr />
<a type="button"
   class="btn"
   href="#article-editor"
   data-toggle="modal">Cars in Popup Window</a>

<div class="modal fade panel panel-info" id="article-editor">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h4 class="panel-title">Cars</h4>
    </div>
    <div class="modal-body">
        <div class="panel-body">
            @Html.Grid(Model.CarsInGarage).Columns(col =>
   {
       col.Add(x => x.Name).Titled("Name");
       col.Add(x => x.Year).Titled("Year");
       col.Add(x => x.RegistrationDate).Titled("RegistrationDate").Format("{0:dd/MM/yyyy}").Titled("RegistrationDate");
       col.Add().Sanitized(false).Encoded(false).RenderValueAs(x => Menu(x));
   }).WithPaging(5)
        </div>

    </div>
    <div class="modal-footer">
        <a href="#" class="btn" data-dismiss="modal">Close</a>
    </div>
</div>

<hr />
<div class="panel panel-info">
    <div class="panel-heading">
        <h4 class="panel-title">Cars</h4>
    </div>
    <div class="panel-body">
        @Html.Grid(Model.CarsInGarage).Columns(col =>
   {       
       col.Add(x => x.Name).Titled("Name").Filterable(true).Sortable(true);
       col.Add(x => x.Year).Titled("Year").Filterable(true).Sortable(true);
       col.Add(x => x.RegistrationDate).Titled("RegistrationDate").Format("{0:dd/MM/yyyy}").Titled("RegistrationDate").Filterable(true).Sortable(true);
       col.Add().Sanitized(false).Encoded(false).RenderValueAs(x => Menu(x));
   }).WithPaging(5)
    </div>
</div>
<p>
    @Html.ActionLink("Edit Garage", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>


@helper Menu(car_park.WEB.Models.CarVM vm)
{
    <a href="@Url.Action("Edit", "Car", new { ID = vm.ID })">Edit</a>   
}

car-park.WEB/Views/Garage/Edit.cshtml
@model car_park.WEB.Models.GarageVM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Garage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MaxCar, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MaxCar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MaxCar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

car-park.WEB/Views/Garage/Index.cshtml
@model IEnumerable<car_park.WEB.Models.GarageVM>
@using GridMvc.Html

@{
    ViewBag.Title = "Garage List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Garage List</h2>

<p>
    @Html.ActionLink("Create New", "Edit")
</p>
<div class="panel panel-info">
    <div class="panel-heading">
        <h4 class="panel-title">Garages</h4>
    </div>
    <div class="panel-body">
        @Html.Grid(Model).Columns(col =>
   {
       col.Add(x => x.Name).Titled("Name").Filterable(true).Sortable(true);
       col.Add(x => x.Address).Titled("Address").Filterable(true).Sortable(true);
       col.Add(x => x.PhoneNumber).Titled("PhoneNumber").Filterable(true).Sortable(true);
       col.Add(x => x.Email).Titled("Email").Filterable(true).Sortable(true);
       col.Add(x => x.MaxCar).Titled("MaxCar").Filterable(true).Sortable(true);
       col.Add(x => x.CarsInStock).Titled("CarsInStock").Filterable(true).Sortable(true);
       col.Add().Sanitized(false).Encoded(false).RenderValueAs(x => Menu(x));
   }).WithPaging(5)
    </div>
</div>

@helper Menu(car_park.WEB.Models.GarageVM vm)
{
    <a href="@Url.Action("Edit", "Garage", new { ID = vm.ID })">Edit</a>
    <a href="@Url.Action("Details", "Garage", new { ID = vm.ID })">Details</a>
    <a href="@Url.Action("Delete", "Garage", new { ID = vm.ID })">Delete</a>
}